version: '3'

services:
    pg:
        image: postgres:9.6
    rabbit:
        image: rabbitmq:3.6-management
    renderer:
        build: renderer
        environment:
            - NODE_ENV=production
        volumes:
            - ./courses:/tmp/courses-raw
            - data-volume:/tmp/courses-rendered
    reader:
        build: reader
        volumes:
            - data-volume:/tmp/courses-rendered
        environment:
            - NODE_ENV=production
        ports:
            - "8093:8093"

volumes:
    data-volume:
