version: '3'

services:
    pg:
        image: postgres:9.6
        ports:
            - '5432:5432'
    rabbit:
        image: rabbitmq:3.6-management
        ports:
            - '15672:15672'
            - '5672:5672'
    consul:
        image: consul:0.7.5
        ports:
            - '8500:8500'
    validator:
        build: validator
    sandbox:
        build: sandbox
        depends_on:
            - rabbit
    renderer:
        build: renderer
        environment:
            - NODE_ENV=production
        volumes:
            - ./courses:/tmp/courses-raw
            - data-volume:/tmp/courses-rendered
    reader:
        build: reader
        volumes:
            - data-volume:/tmp/courses-rendered
        environment:
            - NODE_ENV=production
        ports:
            - "8093:8093"

volumes:
    data-volume:
