version: '3'

services:
    database:
        image: postgres:9.6
        ports:
            - '5432:5432'
    queue:
        image: rabbitmq:3.6-management
        ports:
            - '15672:15672'
            - '5672:5672'
    consul:
        image: consul:0.7.5
        ports:
            - '8500:8500'
    validator:
        image: codingavenue/ca-school-course-validator-rest-api:latest
    sandbox:
        image: codingavenue/ca-school-sandbox:latest
        depends_on:
            - queue
            - consul
    renderer:
        build: renderer
        environment:
            - NODE_ENV=production
        volumes:
            - ./courses:/tmp/courses-raw
            - data-volume:/tmp/courses-rendered
    reader:
        image: codingavenue/ca-school-reader:latest
        volumes:
            - data-volume:/tmp/courses-rendered
        environment:
            - NODE_ENV=production
        ports:
            - "8093:8093"
    platform:
        image: codingavenue/ca-school-platform:latest
        ports:
            - "8000:8000"
        depends_on:
            - database

volumes:
    data-volume:
