version: '3'

services:
    renderer:
        build: renderer
        volumes:
            - ./courses:/tmp/courses-raw
            - data-volume:/tmp/courses-rendered
    reader:
        build: reader
        depends_on:
            - renderer
        volumes:
            - data-volume:/tmp/courses-rendered
        environment:
            - NODE_ENV=production
        ports:
            - "8093:8093"

volumes:
    data-volume:
