version: '3'

services:
    validator:
        container_name: validator
        image: codingavenue/ca-school-course-validator-rest-api:latest
        ports:
            - '8090:8090'
    sandbox:
        container_name: sandbox
        image: codingavenue/ca-school-sandbox:latest
        ports:
            - '8092:8092'
        networks:
            - app_default
    renderer:
        container_name: renderer
        build: renderer
        environment:
            - NODE_ENV=production
        volumes:
            - ./courses:/tmp/courses-raw
            - data-volume:/tmp/courses-rendered
    reader:
        container_name: reader
        image: codingavenue/ca-school-reader:latest
        volumes:
            - data-volume:/tmp/courses-rendered
        environment:
            - NODE_ENV=production
        ports:
            - "8093:8093"
    platform:
        container_name: platform
        image: codingavenue/ca-school-platform:latest
        ports:
            - "8000:8000"
        networks:
            - app_default

volumes:
    data-volume:

networks:
    app_default:
        external: true
